config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  devise_for :users
  resources :categories
  resources :products do
    resources :reviews
  end
  resources :carts do
    member do
      delete :clear
      get :save
    end
  end

  resource :purchase_history, only: [:show] do
    post 'finalize_purchase', to: 'purchase_histories#finalize_purchase', as: 'finalize_purchase'
  end

  resources :cart_items
  resources :profiles, only: [:show,:edit,:update]
  resources :checkouts, only: [:show, :create] do
    member do
      patch :finalize
      patch :cancel
    end
  end

  resource :wishlist, only: [:show] do
    post 'add_product/:product_id', to: 'wishlists#add_product', as: 'add_product'
    delete :clear
    get :save
    delete 'remove_product/:product_id', to: 'wishlists#remove_product', as: 'remove_product'
  end

  get '/app/javascripts/carousel.js', to: redirect('/app/javascripts/carousel.js')


  root to: 'products#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update]

  def show
    @profile = Profile.find(params[:id])
    @reviews = @profile.reviews
  end

  def edit
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Product was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:bio)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<%= form_for(@profile) do |f| %>
  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="actions">
    <%= f.submit "Update Profile" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="page">
<!--If the profile is the current user's profile-->
<% if @profile.user == current_user %>
  <h2 class="profile-title">Your profile</h2>

  <div class="profile-info">
  <h3 class="profile-info-subtitle">Your email</h3> 
  <p class="profile-email"><%= @profile.user.email %></p>

  <h3 class="profile-info-subtitle">Your bio</h3>
  <p class="profile-bio"><%= @profile.bio %></p>

  <%= button_to 'Edit profile', edit_user_registration_path, method: :get, class: 'edit-profile-btn' %>
  <%= button_to 'Your purchase history', purchase_history_path, method: :get %>
  <!-- if profile is admin, admin can create new category-->
  </div>
  
  
  <div class="product-header">
    <h2 class="profile-title">Your products</h2>
    <div class="add-product-button">
      <%= button_to 'Add Product', new_product_path, method: :get %>
    </div>
    <%if @profile.user.admin==true%>
      <p><%= button_to 'Add Category', new_category_path, method: :get%></p>
    <%end%>
  </div>

  <!--Products-->
  <%if @profile.products==[]%>
    <p>You have no products</p>
  <%else%>
    <% @profile.products.each do |product| %>
    <div class="product-card">
      <div class="product-panel">
        <% if product.images.attached? %>
          <%= image_tag product.images[0], class: "product-image" %>
        <%end%>
        <h3><%= link_to product_path(product), class: "product-name" do %>
          <span class="product-link"></span>
          <%= product.name %>
        <% end %></h3>
        <div class="product-category-price-layout">
          <p class="product-category"><%= product.category.name %></p>
          <p class="product-price">Price: <%= number_to_currency(product.price) %></p>
        </div>
      </div>
      <div class="delete-button-container">
        <%= button_to edit_product_path(product), method: :get, class: 'edit-button' do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= button_to product_path(product), method: :delete, class: 'delete-button' do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
    </div>
    <% end %>
  <% end %>
  

  <!--Reviews-->
  <h2 class="profile-title">Your reviews</h2>
  <% if @reviews==[] %>
    <p>You have no reviews</p>
  <%else%>
  <% @reviews.each do |review| %>
    <div class="product-card">
      <div class="product-panel">
        <% if review.product.images.attached? %>
          <%= image_tag review.product.images[0], class: "product-image" %>
        <%end%>
        <h3><%= link_to product_path(review.product), class: "product-name" do %>
          <span class="product-link"></span>
          <%= review.product.name %>
        <% end %></h3>
        <div class="product-category-price-layout">
          <p class="product-category"><%= review.product.category.name %></p>
          <p class="product-price">Price: <%= number_to_currency(review.product.price) %></p>
        </div>
        <div class="review-rating">
          <% review.rating.times do %>
            <i class="fas fa-star star-on"></i>
          <% end %>
          <% (5 - review.rating).times do %>
            <i class="fas fa-star star-off"></i>
          <% end %>
        </div>
        <p class="review-content"><%= review.content %></p>
      </div>
      <div class="delete-button-container">
        <%= button_to edit_product_review_path(review.product_id,review), method: :get, class: 'edit-button' do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= button_to product_review_path(review), method: :delete, class: 'delete-button' do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
    </div>
  <% end %>
  <% end %>
  
<!--If the profile is not the current user's profile-->
<% else %>
  <h2 class="profile-title">This is the profile of <%= @profile.user.email %></h2>
  <p class="profile-bio"><%= @profile.bio %></p>
  <h2>Reviews</h2>
  <% @reviews.each do |review| %>
    <p><%= review.content %> - <%= review.rating %>/5</p>
    <p>Reviewed product: <%= link_to review.product.name, product_path(review.product) %></p>
  <% end %>

  <h2>Products</h2>
  <%if @profile.products==nil%>
    <p>This profile has no products.</p>
  <%else%>
    <% @profile.products.each do |product| %>
      <h3><%= link_to product.name, product_path(product) %></h3>
      <% if product.images.attached? %>
        <%= image_tag product.images[0]%>
      <%end%>
      <p><%= product.description %></p>
      <p>Price: <%= number_to_currency(product.price) %></p>
    <%end%>
  <% end %> 
<% end %>
</div>