config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  devise_for :users
  resources :categories
  resources :products do
    resources :reviews
  end
  resources :carts do
    member do
      delete :clear
      get :save
    end
  end

  resource :purchase_history, only: [:show] do
    post 'finalize_purchase', to: 'purchase_histories#finalize_purchase', as: 'finalize_purchase'
  end

  resources :cart_items
  resources :profiles, only: [:show,:edit,:update]
  resources :checkouts, only: [:show, :create] do
    member do
      patch :finalize
      patch :cancel
    end
  end

  resource :wishlist, only: [:show] do
    post 'add_product/:product_id', to: 'wishlists#add_product', as: 'add_product'
    delete :clear
    get :save
    delete 'remove_product/:product_id', to: 'wishlists#remove_product', as: 'remove_product'
  end

  get '/app/javascripts/carousel.js', to: redirect('/app/javascripts/carousel.js')


  root to: 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :profile

  has_many :reviews, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many_attached :images
  has_and_belongs_to_many :wishlists

  accepts_nested_attributes_for :category, reject_if: :all_blank

  validates :name, :description, :price, :category_id, :profile_id, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @categories = Category.all
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
    @category = Category.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @categories = Category.all # This line sets @categories
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        @categories = Category.all
        @category = Category.new
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if product_params[:images]!=[""]
        if @product.update(product_params)
          format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      else
        if @product.update(product_params_without_images)
          format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to profile_url(current_user.id), notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.

    def product_params_without_images
      params.require(:product).permit(:name, :description, :price, :category_id, :profile_id)
    end
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :profile_id, images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true, multipart: true, ) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2 class="login-heading"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Product Name", class: "input-field" %>
  </div>

  <div class="field">
    <%= form.text_area :description, placeholder: "Product Description", class: "input-field" %>
  </div>

  <div class="field">
    <%= form.number_field :price, step: :any, placeholder: "Product Price", class: "input-field" %>
  </div>

  <div class="field">
    <%= form.collection_select :category_id, @categories, :id, :name, { prompt: true }, { class: "input-field" } %>
  </div>

  <div class="field">
    <%= form.hidden_field :profile_id, value: current_user.profile.id %>
  </div>

  <div class="field">
    <%= form.label :images, 'Images', class: "input-label" %>
    <%= form.file_field :images, multiple: true, class: "input-field" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <div class="sign-up">
  <%= link_to "Back to products", products_path %>
</div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>s
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= product.user_id %>
  </p>

</div>

app/views/products/edit.html.erb
<div class='login-form'>
  <h1 class="login-heading">Editing product</h1>

  <%= render "form", product: @product %>

  <br>

  <div>
    <%= link_to "Show this product", @product %> |
    <%= link_to "Back to products", products_path %>
  </div>
</div>

app/views/products/index.html.erb
<div class="page">
<h1 class="hero-title">
  Welcome to the
  <span class="shop-name">Boring Shop</span>
</h1>
<% @categories.each do |category| %>
  <% next if category.products.empty? %>
  <h2 class="category-title"><%= category.name %></h2>
  <% category.products.each do |product| %>
    <div class="product-card">
      <div class="product-panel">
        <% if product.images.attached? %>
          <%= image_tag product.images[0], class: "product-image" %>
        <%end%>
        <h3><%= link_to product_path(product), class: "product-name" do %>
          <span class="product-link"></span>
          <%= product.name %>
        <% end %></h3>
        <div class="product-category-price-layout">
          <p class="product-price product-price-index">Price: <%= number_to_currency(product.price) %></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div

app/views/products/new.html.erb
<div class='login-form'>
<h1 class="login-heading">New product</h1>

<%= render "form", product: @product %>

<br>
</div>

app/views/products/show.html.erb
<div class="page">
    <div class="left-column">
        <div class="carousel-container">
            <div class="carousel" id="carousel-1" auto-scroll="7000">
                <% @product.images.each do |image| %>
                    <section class="carousel-screen">
                        <%= image_tag image, class: "product-image" %>
                    </section>
                <% end %>
                <div class="left-arrow">
                    <span class="chevron left"></span>
                </div>
                <div class="right-arrow">
                    <span class="chevron right"></span>
                </div>
            </div>
            <section class="circle-container">
                    <% @product.images.each do |image| %>
                        <div class="circle"></div>
                    <% end %>
            </section>
        </div>
        <div class="right-column">
            <h1 class="product-page-name"><%= @product.name %></h1>
            <p class="product-page-category">Category: <%= @product.category.name %></p>
            <p class="product-page-price"><%= number_to_currency(@product.price) %></p>
            <%= form_with model: CartItem.new, url: cart_items_path, method: :post, local: true do |f| %>
            <div class="quantity-container">
                <button type="button" id="minus-btn" class="quantity-btn"><i class="fas fa-minus"></i></button>
                <span id="quantity-display">1</span>
                <button type="button" id="plus-btn" class="quantity-btn"><i class="fas fa-plus"></i></button>
            </div>
            <%= f.hidden_field :product_id, value: @product.id %>
            <%= f.hidden_field :quantity, value: 1, id: 'quantity-field' %>
            <%= f.submit 'Add to Cart', class: "submit-btn"%>
            <% end %>
            <%= button_to 'Add to Wishlist', add_product_wishlist_path(@product), method: :post, class: 'wishlist-btn' %>
            <p class="product-page-seller">Seller: <%= link_to @product.profile.user.email, profile_path(@product.profile) %></p>

            <script>
            document.addEventListener('DOMContentLoaded', function () {
                const minusBtn = document.getElementById('minus-btn');
                const plusBtn = document.getElementById('plus-btn');
                const quantityDisplay = document.getElementById('quantity-display');
                const quantityField = document.getElementById('quantity-field');

                minusBtn.addEventListener('click', function () {
                let currentValue = parseInt(quantityDisplay.innerText, 10);
                if (currentValue > 1) {
                    quantityDisplay.innerText = currentValue - 1;
                    quantityField.value = currentValue - 1;
                }
                });

                plusBtn.addEventListener('click', function () {
                let currentValue = parseInt(quantityDisplay.innerText, 10);
                quantityDisplay.innerText = currentValue + 1;
                quantityField.value = currentValue + 1;
                });
            });
            </script>

        </div>
    </div>
    <h2 class="product-page-description-title">Description</h2>
    <p class="product-page-description" ><%= @product.description %></p>

    <% if user_signed_in? && current_user!=@product.profile.user && current_user.profile.reviews.find_by(product: @product)==nil %>
        <h3 class="product-page-description-title">Leave a Review</h3>
        <%= form_with(model: [@product, @product.reviews.build], local: true, html: { class: 'review-form' }) do |form| %>
            <div class="star-rating">
            <% 5.times do |i| %>
                <i class="fas fa-star star-off" data-value="<%= i + 1 %>"></i>
            <% end %>
            </div>
            <%= form.hidden_field :rating, id: 'review_rating' %>
            <div>
            <%= form.text_area :content, class: 'content-textarea', placeholder: 'Your review...' %>
            </div>
            <div>
            <%= form.submit %>
            </div>
        <% end %>
    <% end %>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
    const stars = document.querySelectorAll('.star-rating .fa-star');
    const ratingInput = document.getElementById('review_rating');

    stars.forEach(star => {
        star.addEventListener('mouseover', handleMouseOver);
        star.addEventListener('mouseout', handleMouseOut);
        star.addEventListener('click', handleClick);
    });

    function handleMouseOver(event) {
        const value = parseInt(event.target.getAttribute('data-value'));
        highlightStars(value);
    }

    function handleMouseOut() {
        const selectedValue = parseInt(ratingInput.value) || 0;
        highlightStars(selectedValue);
    }

    function handleClick(event) {
        const value = parseInt(event.target.getAttribute('data-value'));
        ratingInput.value = value;
        highlightStars(value);
    }

    function highlightStars(value) {
        stars.forEach(star => {
        const starValue = parseInt(star.getAttribute('data-value'));
        if (starValue <= value) {
            star.classList.add('star-on');
            star.classList.remove('star-off');
        } else {
            star.classList.add('star-off');
            star.classList.remove('star-on');
        }
        });
    }
    });
    </script>
    
    <h2 class="product-page-description-title">Reviews</h2>
    <% @reviews.each do |review| %>
        <% if review.profile.present? && review.rating.present? %>
        <div class="review">
            <div class="review-rating product-page-review-rating">
                <% review.rating.times do %>
                    <i class="fas fa-star star-on"></i>
                <% end %>
                <% (5 - review.rating).times do %>
                    <i class="fas fa-star star-off"></i>
                <% end %>
                <p class="product-page-reviewer"><%= link_to review.profile.user.email, profile_path(review.profile) %></p>
                <% if !current_user.nil? and  review.profile_id==current_user.id%>
                <div class="review-edit-button-container">
                    <%= button_to edit_product_review_path(@product, review), method: :get, class: 'edit-button' do %>
                        <i class="fas fa-edit"></i>
                    <% end %>
                </div>
                <%end%>
            </div>
            <p class="product-page-review-content"><%= review.content %></p>
            <!--if is review owner is current user show button to edit review-->
        </div>
        <% end %>
    <% end %>
    <!--if owner of the product is current user show button to edit product-->
    <!--
    <% if !current_user.nil? and @product.profile_id==current_user.id%>
            <div class="edit-button-container">
        <%= button_to edit_product_path(@product), method: :get, class: 'edit-button' do %>
            <i class="fas fa-edit"></i>
        <% end %>
        </div>
    <%end%>
    -->

    <%= javascript_include_tag 'carousel', 'data-turbolinks-track': 'reload' %>
<div class="page">