config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  devise_for :users
  resources :categories
  resources :products do
    resources :reviews
  end
  resources :carts do
    member do
      delete :clear
      get :save
    end
  end

  resource :purchase_history, only: [:show] do
    post 'finalize_purchase', to: 'purchase_histories#finalize_purchase', as: 'finalize_purchase'
  end

  resources :cart_items
  resources :profiles, only: [:show,:edit,:update]
  resources :checkouts, only: [:show, :create] do
    member do
      patch :finalize
      patch :cancel
    end
  end

  resource :wishlist, only: [:show] do
    post 'add_product/:product_id', to: 'wishlists#add_product', as: 'add_product'
    delete :clear
    get :save
    delete 'remove_product/:product_id', to: 'wishlists#remove_product', as: 'remove_product'
  end

  get '/app/javascripts/carousel.js', to: redirect('/app/javascripts/carousel.js')


  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :purchase_history, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  has_one :checkout, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/checkout.rb
class Checkout < ApplicationRecord
  belongs_to :cart
  enum status: { pending: 'pending', finalized: 'finalized', cancelled: 'cancelled' }

  def order_summary
    cart_items = cart.cart_items.includes(:product)
    summary = cart_items.map do |item|
      {
        product_name: item.product.name,
        quantity: item.quantity,
        price: item.product.price,
        total: item.product.price * item.quantity
      }
    end
    summary << { total_price: cart_items.sum { |item| item.product.price * item.quantity }}
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :profile

  has_many :reviews, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many_attached :images
  has_and_belongs_to_many :wishlists

  accepts_nested_attributes_for :category, reject_if: :all_blank

  validates :name, :description, :price, :category_id, :profile_id, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
  belongs_to :user
  has_many :carts
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :profile
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_one :wishlist, dependent: :destroy
  has_one :purchase_history, dependent: :destroy

  after_create :create_profile
  after_create :create_cart
  after_create :create_purchase_history
  accepts_nested_attributes_for :profile

  def create_purchase_history
    PurchaseHistory.create(user: self) unless purchase_history
  end

  def create_cart
    Cart.create(user: self) unless cart
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    @cart = current_user.cart
    @cart_items = @cart.cart_items
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @cart.destroy!

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def clear
    @cart = current_user.cart
    @cart.cart_items.destroy_all
    redirect_to cart_path(@cart), notice: 'Cart was successfully cleared.'
  end

  def save
    @cart = current_user.cart
    serialized_cart = Marshal.dump(@cart)

    send_data serialized_cart, type: 'application/octet-stream', filename: 'cart_data.bin'
  end

  private
    def set_cart
      @cart = Cart.find(current_user.cart.id)
    end

    def cart_params
      params.require(:cart).permit(:user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  # POST /reviews or /reviews.json
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.profile = current_user.profile

    respond_to do |format|
      if @review.save
        format.html { redirect_to @product, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to profile_url(current_user.id)}
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review = current_user.profile.reviews.find(params[:product_id])
    @product = @review.product
    @review.destroy!

    respond_to do |format|
      format.html { redirect_to @product }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find_by(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:content, :rating, :profile_id, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: [product, review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2 class="login-heading"><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content, placeholder: "Review Content", class: "input-field" %>
  </div>

  <div class="field">
    <%= form.number_field :rating, placeholder: "Rating", class: "input-field" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Review", class: "login-button" %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Content:</strong>
    <%= review.content %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>User:</strong>
    <%= review.profile_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= review.product_id %>
  </p>

</div>

app/views/reviews/edit.html.erb
<div class='login-form'>

<h1>Editing review</h1>

<%= render "form", product: @product, review: @review %>

<br>

<div>
 <!-- <%= link_to "Show this review", product_review_path(@review) %> |-->
  <%= link_to "Back to your profile", profile_path(current_user.id) %>
</div>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<div id="reviews">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", review %>
    </p>
  <% end %>
</div>

<%= link_to "New review", new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_product_review_path(@review) %> |
  <%= link_to "Back to reviews", product_review_path(@review) %>

  <%= button_to "Destroy this review", product_review_path(@review) , method: :delete %>
</div>